### PR TITLE
GitHub Actions for ESOUI releases + DevTools

### PR DESCRIPTION
**Pull request by wookiefriseur**
Hey @manavortex . I got GitHub Actions running on my fork. 😃  I would like to put that in here on the main repo as well so that the next releases can be done with the push of a button (or 3-4 buttons). 

I don't want to merge this without your approval though, because it changes the repo structure a bit and it requires changing settings.

<details><summary>Required settings changes</summary>
<p>

## 1. For this to work it would be best to have `dev` as the main branch:
grafik
(this will make PRs automatically go to dev and when someone clones the repo they get dev by default. I already made the dev branch and I'm pushing this PR to it as well)

## 2. Making the master `protected` wouldn't hurt either, but it's not necessary:
grafik
(this would still allow us to commit directly on master, but it would clearly mark it as protected)

## 3. Enable GitHub Actions (I think you already have them enabled with the default settings, you can check if they are like on the image)
grafik
(this allows only actions to run that are in one of your repos or are created by GitHub and it gives the bot PR permissions. The bot uses a token automatically generated for each job, it has only repo access)

## 4. Add ESOUI_API_TOKEN to secrets
grafik
(required to talk to the ESOUI API. You can get it [here](https://www.esoui.com/downloads/filecpl.php?action=apitokens) or I can send you mine securely)

## 5. While you're in the settings you can disable projects and enable discussions
Just a suggestion, I think discussions could be useful and projects are overkill. The Wiki could be useful later if we have stuff we don't want to put into the README.

</p>
</details> 

# Changes

@BerylBones : The only thing that would change for you is that you would send your PRs to `dev` instead of master, but this branch will always be the default target if you create a PR, so no worries. And you will not have to change version numbers anywhere, that will happen automatically. I also will take care of any labels or releases.

- GitHub Actions
    - updates versions and changelog depending on labels and notes 
    - creates a release and publishes it to ESOUI
    - publishing is currently sending the update request to [updatetest](https://api.esoui.com/addons/updatetest) instead of [update](https://api.esoui.com/addons/update)
    - so no worries, we can't break anything with it on the ESOUI page
    - when we have a real release we can change 1 line of code to set it live
- DevTools changes
- I accidentally also added automatic formatting changes (spaces, indentations, newlines)
    - and some code that was meant for the other PR
    - it makes this PR seem bigger than it is, but it's mostly just formatting
    - it would be too much work to remove it all again
    - it's running on the current game client and has no breaking changes

# The workflow I was thinking of

I went full nerd and made a picture 🤓 

grafik

See also [an example workflow in my guide](https://github.com/wookiefriseur/FurnitureCatalogue/blob/dev/docs/CONTRIBUTING.md#recommended-release-flow)

### CODE REVIEW

**Comment by manavortex** [comment]
Awesome! I'm so glad to see FurC in competent hands :))

**Comment by wookiefriseur** [comment]
Oh, hey..  definitely hands, yes. I have those. Competent, maybe?

I am just closing this PR because it looks a bit too big and confusing. Too many mixed changes. I'll split it up into more manageable chunks. 

The GitHub actions and repo changes would be cool and I hope you enable them, but you don't have to. I can also use actions from my own repo and then update it here after each release. 😸

**Comment by manavortex** [comment]
Can you tell me where to click? I've never done that before :D 
You don't have rights to do that? :D

**Comment by wookiefriseur** [comment]
Oh, yeah, I put some screenshots in the first post but they are folded. Here they are again:

---

## 1. For this to work it would be best to have `dev` as the main branch:
**Use the double arrow icon, not the pencil**
grafik
(this will make PRs automatically go to dev and when someone clones the repo they get dev by default. I already made the dev branch and I'm pushing this PR to it as well)

## 2. Making the master `protected` wouldn't hurt either, but it's not necessary:
grafik
(this would still allow us to commit directly on master, but it would clearly mark it as protected)

## 3. Enable GitHub Actions (I think you already have them enabled with the default settings, you can check if they are like on the image)
grafik
(this allows only actions to run that are in one of your repos or are created by GitHub and it gives the bot PR permissions. The bot uses a token automatically generated for each job, it has only repo access)

## 4. Add ESOUI_API_TOKEN to secrets
grafik
(required to talk to the ESOUI API. You can get it [here](https://www.esoui.com/downloads/filecpl.php?action=apitokens) or I can send you mine securely)

## 5. While you're in the settings you can disable projects and enable discussions
Just a suggestion, I think discussions could be useful and projects are overkill. The Wiki could be useful later if we have stuff we don't want to put into the README.

**Comment by wookiefriseur** [comment]
I found the master+dev thing easier to use with GitHub actions than just having a main branch. Otherwise the bot has to watch all merges and all PRs, also from unknown branches, instead of just looking at certain branches. 

And that way we can play around on the dev branch a bit while master remains up to date with the version on ESOUI.

**Comment by wookiefriseur** [comment]
> As for enabling discussions, I would have done that, but it was not where the [docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/enabling-or-disabling-github-discussions-for-a-repository) said it should be. Ah, well. :D

Oh, yeah.. it's in the repo settings where Wiki and other stuff are:

grafik

**Comment by wookiefriseur** [comment]
@manavortex 

The first automated update seems to have worked: #55 

Thanks for the setting changes.

Can you also switch to dev as the default branch? If you don't want the dev branch and keep it all in master that's ok as well but then I will have to change the scripts and play around with them a bit. 😅

**Pull request closed without merging**
