### PR TITLE
Adding Necrom Items

### PR DESCRIPTION
**Pull request by BerylBones**
I'm running a little bit behind on this update, but I wanted to make sure all the new Necrom items were added before Monday's launch. I'll go through later this week and update some things with known sources like antiquities and paintings.

### CODE REVIEW

**Comment by wookiefriseur** [comment]
Good job! I'll merge it in a few hours when  I had time to check it.

Don't worry about the release. I'll handle the version bump and update. 
Will do it manually this time.

**Comment by BerylBones** [comment]
Ok, sounds good.
I just realized I didn't update the API version in any of the files, but I can do that tomorrow.

**Comment by wookiefriseur** [comment]
> I just realized I didn't update the API version in any of the files

No problem, I'll bump it up to `101038` later.

**Comment by wookiefriseur** [comment]
Yay, I think the release worked. I tested it on PTS and live. Let me know if I broke anything.

**Pull request merged**
