### PR TITLE
API version update for Scribes of Fate DLC

### PR DESCRIPTION
**Pull request by BerylBones**

### CODE REVIEW

**Review by wookiefriseur — APPROVED** [review]
Was not able to confirm all the item changes (because it is so much stuff... BerylBones has been busy 😄  ). But random checks looked good and the AddOn runs fine on my client. I can merge it, if you want @manavortex .

Let me know if you're fine with me merging and releasing in general. (currently preparing a GithubAction for easier releases).

**Comment by manavortex** [comment]
I'm A-OK with that! Knock yourself out! I currently don't even have ESO installed, so the most I can do is peek at the code every now and then and leave some semi-qualified feedback if I notice anything. 

As far as I'm concerned, you have custody of the pony now, and I look at the photos on instagram and say stuff like "but she hates if you do that with the bridle" :D

**Comment by wookiefriseur** [comment]
Alright, I will come crying once something breaks 😁

**Comment by manavortex** [comment]
Extremely fair lmao

**Comment by wookiefriseur** [comment]
Just for info and future historians: Looks like this version is already part of the latest release `4.71`! BerylBones must have released this and a hotfix similar to f14f5bba62d96206f1632f97d1469dc23f993b46 months ago. Always a step ahead! 😄   I checked the files and we're up to date now. That gives me even more time to play around before the next release.

Also with be7467d2386ca96da078654e2483d7969e29d46c the master and the release also have the same version now.

**Pull request merged**
