### PR TITLE
FurCat 5.0: Overhaul suggestions and questions

### PR DESCRIPTION
**Pull request by wookiefriseur**
Hey there @manavortex 

I've been working on some updates to FurnitureCatalogue and created this draft PR to discuss my plans and potential changes. I don't know how involved you still are with the development process, besides doing the releases and version bumps. Usually I send PRs to @BerylBones but because it's about major changes and this is your baby I wanted to get your blessing and suggestions first.

## Planned Changes

1. migrate character knowledge to [LibCharacterKnowledge](https://www.esoui.com/downloads/info3317-LibCharacterKnowledge.html) (WIP)
    - right now it's being stored in SavedVars, which can grow quite in size
2. split DB into a separate Library `LibFurniture`
    - see https://github.com/BerylBones/FurnitureCatalogue/issues/16
    - WIP, would be inside FurnitureCatalogue first and then be moved out into its own AddOn
    - might also move `FurnitureCatalogue_Export` functions into the library (with optional dependency on LibCharacterKnowledge)
3. create API for `LibFurniture`, allowing other AddOns to utilise it
4. add filter for furniture categories
    - see https://github.com/BerylBones/FurnitureCatalogue/issues/5 
5. streamline deployment process with GitHub Actions or scripts
    - for instance auto deploy on master merge or 1-click deployment to ESOUI
6. improve the item data collection process to make it more user-friendly
    - this could include options such as CSV or Lua imports
    - or some mix of automatically exported and manually entered data
    - or an in-game interface that allows users to submit item details through a generated URI with GET parameters

## Implemented so far

1. restructured the devtools and moved them into `FurnitureCatalogue_DevUtility`
2. reworked the packaging script for zip releases (batch is hard 😅 )
3. fixed some duplicate entries and little bugs here and there
4. cleaned the global tables and constants a bit
5. removed unused libraries and variables

Also fixed in this draft PR:
- https://github.com/BerylBones/FurnitureCatalogue/issues/17
- https://github.com/BerylBones/FurnitureCatalogue/issues/15
- https://github.com/BerylBones/FurnitureCatalogue/issues/14
- as well as other changes you can see in the [diff view](https://github.com/manavortex/FurnitureCatalogue/pull/31/files?diff=unified&w=1)

## Maintainers

Final point: If possible, I'd like to be added as a maintainer for the core AddOn (this repo) or take over maintenance, while also providing BerylBones and you with full co-authoring control of both the core AddOn and the separate DB library. I think BerylBones was mostly doing regular database updates so that would not have to change. And if you decide to start playing again you could take over any time. 

I would understand it if you didn't want to do this. Then at least let me know what you think of the plans and if there is anything I can help you with.

### CODE REVIEW

**Comment by manavortex** [comment]
Hey there, 

thank you so much for keeping me in the loop - I've stopped playing ESO shortly after Summerset, and I just keep an eye on my addons' esoui notification mails because I made them and I don't want to abandon them next to the highway. I'm glad that Beryl and you keep things going!

I didn't really have time yet to look at the pull request (just woke up), I'll check if I can look today and maybe leave some feedback regarding coding style. I'm still extremely fond of FurC, I think it's the least terrible code I've ever published, and I'm glad to see it in loving hands :) So I added you as collaborator. If/when the two of you burn out or move on, I hope there's enough documentation for the next person to pick up the torch!

**Comment by wookiefriseur** [comment]
Thanks for the quick response. It's my favourite AddOn, that's why I wanted to keep working on it and improve it where I can. 

It's just a draft to show the direction this could be going in so that you can step in if you see anything you don't like. I recommend viewing the diff without whitespaces, because there was a lot of automatic indentation and space changes. It took me a while to get to know the code a bit better, and it's still an ongoing process for me. It's really a lot of stuff. Character Knowledge is currently broken except for tooltips, because I just committed mid change.

There is currently more than a month left for the next game patch, so don't feel rushed.

---

Oh, wow. Thanks a lot for adding me as a collaborator. Did not expect it this fast, 

Just let me know if and when you want me to take care of merges, releases and uploads. I will have to look at all the settings and possible GitHub actions later. 

I think I will also have to ask Baertram to add me to FurnitureCatalogue on ESOUI so that I can upload releases. If that doesn't work I think we can also use [an API token](https://www.esoui.com/downloads/filecpl.php?action=apitokens) from you or Beryl.

**Comment by manavortex** [comment]
Hey, 
if you give me your ESOUI username, I can probably do that as well (adding you to the team, I mean) :D Say hi to the other children for me!

Thank you for the kind words regarding the addon. It was my attempt to cope with suddenly being drowned in housing items. When Morrowind hit, I spent 2 whole weeks of vacation on completely rewriting it with the current structure where everything is grouped by game version, since that made it easiest to add new items... LibCharacterKnowledge didn't exist back then (baer or siri? Or someone new?) 

Anyhow, I'm glad to see this being developed further!

**Comment by manavortex** [comment]
Yes, same :D The integration with AwesomeGS was So Good back then.

BTW: You’re a team member, Harry!

**Comment by BerylBones** [comment]
Sorry I'm a bit behind on what's happening, but I definitely appreciate having you step up to take over the coding updates! I'm happy to continue with the item updates, just let me know if your changes will affect how I need to do that!

**Comment by wookiefriseur** [comment]
Hey, no worries. It turned out that actually I was the one behind. I was trying to prepare the release for #30 but you already did it in march 😅 

No database changes yet. Only thing that might change soon but not yet is that the `data` folder might be inside a `LibFurniture` folder. Like so:

```
# Before:
FurnitureCatalogue
-- data

# After:
FurnitureCatalogue
-- LibFurniture
---- data
```

In the future I plan to create some kind of helper to make it even easier. I would like your feedback when I start with that feature, because you are way more familiar with the item updates than me. Only recently did it myself for testing purposes.

**Pull request closed without merging**
